### PR TITLE
Remove `AsyncTasks`

### LINKED ISSUE #416: Get rid of `LeanCode.AsyncTasks`?
It was mainly for two things
- scheduling some work for the future 
- long running background tasks

For both cases we tend to use other means now, MassTransit scheduling and (more recently) MassTransit job consumers that better integrate with the rest of our ecosystem.

### PR DESCRIPTION
**Pull request by jakubfijalkowski**
Closes #416

### CODE REVIEW

**Review by marcin-dardzinski — APPROVED** [review]
Pls also remove leftovers from `Directory.Build.targets`

**Comment by jakubfijalkowski** [comment]
@marcin-dardzinski which one? Hangfire is used by the integration tests also.

**Comment by marcin-dardzinski** [comment]
Hmm, so you kept hangfire initializer for tests? :thinking:
Don't see a reason why we should keep it there, I'd say wipe it there as well.

**Comment by jakubfijalkowski** [comment]
I kept it as an example on how to do it - in the end, there are still some projects that use Hangfire.

But maybe you're right. We haven't used it for a long time.

**Pull request merged**
