### PR TITLE
Ordered hosted service

### PR DESCRIPTION
**Pull request by jakubfijalkowski**
This PR replaces the custom `IAsyncInitializable` with a slightly modified version of an `IHostedService` that supports number-ordering. This is mostly the same code but with slightly changed naming. I've also ported everything in the repo to use that.

I'm starting to think that using this kind of ordering is flawed. The more I think about it, the more I'm for using registration order. The only thing that makes me not want to go with plain `IHostedService` is that ASP.NET Core [does not reverse the services when stopping](https://github.com/dotnet/aspnetcore/blob/v5.0.0/src/Hosting/Hosting/src/Internal/HostedServiceExecutor.cs#L29-L65) and we *do* have cross-service dependencies. We could change that by splitting them in two (i.e. `StartAsync` implemented in one class, `StopAsync` in the other) and ensuring that they are placed correctly, but this will be terribly fragile. :(

Solves (partly) #56

### CODE REVIEW

**Review by lukaszgarstecki — APPROVED** [review]

**Review by Saancreed — APPROVED** [review]
While the code itself is fine, I don't really understand why continuing to use `IAsyncInitializable` would be a problem and why do we need this breaking change to fix it.

**Comment by jakubfijalkowski** [comment]
I hated the naming. `Initializable` suggests that we're doing initialization only, but if you look at `PeriodicAction` or `MassTransitHostedService`, these are really background services, so the name doesn't match the purpose. Also, I want to somewhat re-use the `IHostedService` infrastructure if we ever (and I really hope so) wish to get rid of this.

Also, I'm not sure whether that is the correct approach. It seems to me it is better named now, but I'm not sure whether it should ever exist in the first place.

**Comment by Saancreed** [comment]
Perhaps we could file an issue about the order of stopping hosted services to aspnetcore repo, maybe we will find some resolution there.

**Comment by jakubfijalkowski** [comment]
Yeah, you're right, I will send one.

**Comment by jakubfijalkowski** [comment]
Here you go: https://github.com/dotnet/aspnetcore/discussions/28540

**Comment by jakubfijalkowski** [comment]
I'm merging this so that we get at least _some_ improvement here.

**Pull request merged**
