### PR TITLE
MassTransit module registration

### PR DESCRIPTION
**Pull request by jakubfijalkowski**
The module registered periodic services but forgot to register the classes that will be run. Also, there was slight mismatch in `SaveChangesAsync` type and the MT docs weren't linked to, so I changed that.

### CODE REVIEW

**Comment by jakubfijalkowski** [comment]
Aand `dependabot.yml` location fix.

**Comment by marcin-dardzinski** [comment]
Wait, `services.AddHostedService` doesn't register it in the container? :open_mouth: Sounds exactly what the method will do

**Review by marcin-dardzinski — APPROVED** [review]

**Comment by jakubfijalkowski** [comment]
It does register the `IHostedService`, but since you're registering `PeriodicHostedService<T>` that takes the `T` as ctor parameter, you need to register it also (the `T`). :)

**Review by lukaszgarstecki — APPROVED** [review]

**Comment by marcin-dardzinski** [comment]
Oh, okay :stuck_out_tongue:

**Pull request merged**
